package com.multi.customer_service.web;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2024-12-04T15:58:54.860+01:00
 * Generated source version: 4.0.3
 *
 */
@WebService(targetNamespace = "http://web.customer_service.multi.com/", name = "CustomerSOAPController")
@XmlSeeAlso({ObjectFactory.class})
public interface CustomerSOAPController {

    @WebMethod
    @RequestWrapper(localName = "allCustomers", targetNamespace = "http://web.customer_service.multi.com/", className = "com.multi.customer_service.web.AllCustomers")
    @ResponseWrapper(localName = "allCustomersResponse", targetNamespace = "http://web.customer_service.multi.com/", className = "com.multi.customer_service.web.AllCustomersResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.multi.customer_service.web.Customer> allCustomers()
;

    @WebMethod
    @RequestWrapper(localName = "customerById", targetNamespace = "http://web.customer_service.multi.com/", className = "com.multi.customer_service.web.CustomerById")
    @ResponseWrapper(localName = "customerByIdResponse", targetNamespace = "http://web.customer_service.multi.com/", className = "com.multi.customer_service.web.CustomerByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.multi.customer_service.web.Customer customerById(

        @WebParam(name = "id", targetNamespace = "")
        java.lang.Long id
    );

    @WebMethod
    @RequestWrapper(localName = "saveCustomer", targetNamespace = "http://web.customer_service.multi.com/", className = "com.multi.customer_service.web.SaveCustomer")
    @ResponseWrapper(localName = "saveCustomerResponse", targetNamespace = "http://web.customer_service.multi.com/", className = "com.multi.customer_service.web.SaveCustomerResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.multi.customer_service.web.Customer saveCustomer(

        @WebParam(name = "customer", targetNamespace = "")
        com.multi.customer_service.web.CustomerDTO customer
    );
}
